### ISSUE TITLE
clojure.tools.namespace does not find test directory when used with boot

### ISSUE THREAD

**Issue by jasongilman** [jasongilman/proto-repl-demo#5]
I'm not sure that I have boot setup correctly for the proto-repl-demo project. The test directories are not loaded when refresh is run.

**Comment by phreed** [comment]
I am making a pull request related to this.

**Comment by phreed** [comment]
No, there is still something not right. I will take another look.

**Comment by phreed** [comment]
The principle _boot_ start-up sequence seems to be...
0) run the boot.sh 
0.1) which starts Boot.main https://github.com/boot-clj/boot-bin/blob/master/src/Boot.java
1) https://github.com/boot-clj/boot/blob/master/boot/base/src/main/java/boot/App.java
1.1) some default values for the properties are set 
1.2) 'boot.properties' are read, possibly overwriting  default properties
2) boot helper actions are evaluated {update, version}
3) Clojure is started
3.1) the clojure.main is not invoked http://clojure.org/reference/repl_and_main therefore, 
3.1.1) 'user.clj' is ​_not_​ loaded,
3.1.2) nor any of the other attendent behavior (init, eval, etc.}
3.2) boot.main/-main is invoked (instead of clojure.main/-main)
3.2.1) we call runBoot which makes a Clojure call and we say good-bye to Java
3.2.2) -main in  https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/main.clj
4) boot takes control
4.1) the 'boot.user' namespace is constructed 
4.1.1) the 'profile.boot' is included in 'boot.user'
4.1.2) the 'build.boot' is included in 'boot.user'
4.2) the boot.core/init! is run https://github.com/boot-clj/boot/blob/master/boot/core/src/boot/core.clj
4.3) tasks are run

**Comment by phreed** [comment]
@jasongilman : Can you give me a list of all the commands that are sent to Leiningen from proto-repl? {reload, etc.}
I imagine these commands live in the 'user' namespace which is not loaded by boot.  
Adding support for these commands could be added to the 'BOOT_HOME/profile.boot'  or 'build.boot' file.

**Comment by phreed** [comment]
``` clojure
(task-options!
  repl {:init-ns 'user})
```

in build.boot to make it the default
or in profile.boot even

**Comment by jasongilman** [comment]
It runs `lein repl :headless` to start the REPL. Then a refresh is done (depending on the config setting) by executing the following code:

``` Clojure
(do
  (try
    (require 'user)
    (catch java.io.FileNotFoundException e
      (println (str "No user namespace defined. Defaulting to clojure.tools.namespace.repl/refresh.\n"))))
  (try
    (require 'clojure.tools.namespace.repl)
    (catch java.io.FileNotFoundException e
      (println "clojure.tools.namespace.repl not available. Add as a dependency to allow refresh.")))
  (let [user-reset 'user/reset
        ctnr-refresh 'clojure.tools.namespace.repl/refresh
        result (cond
                 (find-var user-reset)
                 ((resolve user-reset))

                 (find-var ctnr-refresh)
                 ((resolve ctnr-refresh))

                 :else
                  (println (str "You can use your own refresh function, just define reset function in user namespace\n"
                                "See this https://github.com/clojure/tools.namespace#reloading-code-motivation for why you should use it")))]
    (when (isa? (type result) Exception)
      (println (.getMessage result)))
    result))
```

Do you think that task option would solve the problem you're seeing?

**Comment by jasongilman** [comment]
The latest on master has refresh working and tests are seen.
