### ISSUE TITLE
Keybindings conflict with atom core on Linux / Ubuntu

### ISSUE THREAD

**Issue by practicalli-johnny** [jasongilman/proto-repl-demo#7]
The keybindings for evaluating code in a code window conflict with the atom core keybindings

For example: `ctrl-, b` opens up the atom keybindings window.

All the proto-repl keybindings that start with `ctrl-,` seem to conflict

**Comment by jasongilman** [comment]
If you press ctrl and comma and then b very soon afterwards does it still do that?

Someone had reported this before in Windows but the preferences were opened up if you paused long enough between pressing them. Doing them quickly in succession will not open preferences.

**Comment by practicalli-johnny** [comment]
The settings always appear no mater how fast I type the b, even typing it almost simultaneously.  I have tried two versions of Ubuntu and ensured I am running the latest version of atom.io.

**Comment by jasongilman** [comment]
This was the issue that was reported before on windows: https://github.com/jasongilman/proto-repl/issues/56 It ended up not being a problem there because of the pause before settings opened. I wasn't sure that I should stick with ctrl-, because of the possibility of issues. Here's what I put on the other issue as a possible solution:

> I'd like to keep them very close to the current one since people may be building up muscle memory. Here are some potential ones I rejected:
> 
> ctrl-shift-, This is actually ctrl-< and is already bound to something.
> ctrl-. (period is next to comma). This brings up the Keybinding Resolver on windows and linux.
> ctrl-/ (/ is close to comma) Already bound to comment code.
> ctrl-space - This may be already bound to application launchers.
> I'm leaning towards making the keybindings ctrl-alt-, for windows and linux users and leaving it as ctrl-, for mac users.

What do you think about that solution? Can you test ctrl-alt-, on to see if anything else uses that? It's tricky to find the right bindings that won't conflict.

**Comment by practicalli-johnny** [comment]
Hmm, the bizarre thing is that `ctrl-, b` and other commands are now working okay.  I don't believe I have changed anything, however I have restarted atom.io a few times.

`ctrl-alt-,` is not bound to anything I have on atom.io.  I only have the proto-repl plugin installed in atom.io

I will do some more testing over the next week or two and see if this issue re-occurs.

**Comment by jasongilman** [comment]
do you think it's possible you restarted atom since you installed Proto REPL and then it started working? I'm wondering if right after installation it won't work until restarted.

**Comment by practicalli-johnny** [comment]
I am sure that I restarted atom.io several times over several day after
installing Proto REPL when trying to make the key bindings work.

I will be reinstalling my laptop in a couple of weeks, so will try atom.io
and Proto REPL again and take note of when this issue arrises and how often
I restated atom.io.

Thanks

Thanks
John
| jr0cket.co.uk | @jr0cket http://www.twitter.com/jr0cket | Google+
https://plus.google.com/u/0/117080433375668558463/ | LinkedIn
http://uk.linkedin.com/in/jr0cket |

**Comment by mkno** [comment]
running into this exact issue on win 7, pressing ctrl-, will spawn settings 

not impressed by the initial experience

**Comment by jasongilman** [comment]
Sorry to hear about that. I was alerted to this issue a while ago by a user on Windows but then they closed the issue and said it actually worked because you can hit the keystrokes and it will invoke the keybinding. It will only open preferences if you pause long enough between keystrokes. 

I could try using a different keybinding. I had done some research before and found a few that would work. It's tricky because as soon as I find the perfect keybinding I hear from a user that it conflicts with another package. 

I chose comma because I looked to how Sublime REPL worked which was a popular version with sublime text. Do you have any suggestions for improvement?

**Comment by Giesch** [comment]
I'm on windows 10, and the problem is inconsistent; I'm not sure why. Changing the atom settings to ctrl-, shift-S was an easy fix.

**Comment by jasongilman** [comment]
I've published a new version of proto repl which changes the keybinding initiator from `ctrl-,` to `ctrl-alt-,`. I left the old keybindings in place to avoid breaking existing users' workflows. I don't think this will interfere with opening preferences as most of the feedback was the preferences opened when you didn't want them to. If there are still problems please comment here.

Thanks for providing the feedback. For every user who reports a problem here I'm sure there are 10 who are experiencing it.

**Comment by ghost** [comment]
I was able to fix this on my machine by getting rid of the commas and spaces in the ~/.atom/packages/proto-repl/keymaps/proto-repl.cson file.  For example, changing the following entry:

'ctrl-alt-, l': 'proto-repl:toggle'

to

'ctrl-alt-l': 'proto-repl:toggle'

enables the keyboard shortcut to start the REPL.
